/* Real Edge browser checks, isolated profile; also records the actual workflow. */
const fs = require('node:fs');
const path = require('node:path');
const assert = require('node:assert/strict');
let playwright;
try { playwright = require('playwright'); }
catch { playwright = require(path.join(process.env.USERPROFILE, '.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright')); }
const root = path.resolve(__dirname, '..');
const out = path.join(root, 'deliverables');
const base = process.env.DEMO_URL || 'http://127.0.0.1:8765';
const record = process.argv.includes('--record');
const taskTitle = record ? '录屏演示：核实使用不适并跟进' : '演示：核实使用不适并跟进';
const wait = async (page, ms=3500) => { if (record) await page.waitForTimeout(ms); };

(async()=>{
  fs.mkdirSync(out,{recursive:true});
  const browser = await playwright.chromium.launch({headless:true,channel:'msedge'});
  const context = await browser.newContext({viewport:{width:1512,height:982},deviceScaleFactor:1,
    ...(record?{recordVideo:{dir:path.join(out,'recordings'),size:{width:1512,height:982}}}:{})});
  const page = await context.newPage();
  const errors=[];const results=[];
  page.on('pageerror',error=>errors.push(error.message));
  page.on('console',msg=>{if(msg.type()==='error') errors.push(msg.text());});
  page.on('response',r=>{if(r.status()>=400) errors.push(`${r.status()} ${r.url()}`);});
  await page.goto(base);
  await page.locator('.risk-card').first().waitFor();
  await page.getByText('Qwen 未配置 · 已安全回退',{exact:true}).waitFor();
  assert.equal(await page.locator('.session-item').count(),138); results.push('138 sessions render with explicit safe fallback');
  await page.getByRole('button',{name:'配置 Qwen'}).click();
  await page.getByRole('heading',{name:'配置 Qwen + Hybrid'}).waitFor();
  assert.equal(await page.getByLabel('DashScope API Key').getAttribute('type'),'password');
  await page.getByRole('button',{name:'关闭',exact:true}).click();results.push('in-memory Qwen configuration entry is explicit');
  await page.screenshot({path:path.join(out,'01-workspace.png')}); await wait(page,6500);
  await page.getByRole('button',{name:'高关注',exact:true}).click();
  assert.ok(await page.locator('.session-item').count()>0); results.push('risk filter works'); await wait(page);
  await page.getByRole('button',{name:'全部',exact:true}).first().click();
  await page.getByRole('searchbox').fill('S00010');
  assert.equal(await page.locator('.session-item').count(),1);results.push('session search works');await wait(page);
  await page.locator('[data-session="S00010"]').click();
  await page.getByRole('heading',{name:'当前服务事项'}).waitFor();
  assert.ok(await page.locator('.service-item-card').getByText('待核实',{exact:true}).count()>0);
  results.push('time-aware service item card renders');
  await page.getByRole('button',{name:'下一条消息'}).click();
  await page.getByText('2 / 10 条',{exact:true}).waitFor();await wait(page);
  await page.getByRole('button',{name:'下一条消息'}).click();
  await page.getByText('3 / 10 条',{exact:true}).waitFor();await wait(page);
  await page.getByRole('button',{name:'全部',exact:true}).last().click();
  await page.getByText('10 / 10 条',{exact:true}).waitFor();
  assert.equal(await page.locator('.chat-row:not(.simulated)').count(),10);results.push('time replay advances to full history');
  await page.screenshot({path:path.join(out,'02-replay.png')});await wait(page,5000);
  await page.getByRole('tab',{name:'服务轨迹'}).click();
  assert.equal(await page.getByRole('heading',{name:'不良反应工单创建'}).count(),0);
  results.push('future ticket absent through complete chat replay');
  await page.getByRole('button',{name:'归档快照',exact:true}).click();
  await page.getByRole('heading',{name:'不良反应工单创建'}).waitFor();
  results.push('late ticket appears in explicitly labelled archive mode');
  await page.screenshot({path:path.join(out,'03-journey.png')});await wait(page,6000);
  await page.getByRole('tab',{name:'即时洞察'}).click();
  await page.getByRole('button',{name:'回到对话',exact:false}).first().click();
  assert.equal(await page.locator('.message-highlight').count(),1);results.push('evidence jump highlights source');await wait(page);
  await page.screenshot({path:path.join(out,'04-evidence.png')});
  await page.getByRole('button',{name:'采用建议 ↙'}).click();
  assert.ok((await page.getByRole('textbox',{name:'回复草稿'}).inputValue()).length>20);
  await page.getByRole('textbox',{name:'回复草稿'}).fill('已为您完成退款，明天一定到账。');
  await page.getByRole('button',{name:'模拟发送 ↗'}).click();
  await page.getByText('已拦截无依据承诺', {exact:false}).waitFor();
  assert.match(await page.getByRole('textbox',{name:'回复草稿'}).inputValue(),/核实/);
  assert.equal(await page.locator('.simulated').count(),0);results.push('unsafe commitment is downgraded before send');
  await page.getByRole('textbox',{name:'回复草稿'}).fill('理解您希望尽快处理的心情。我会整理您已经提供的信息交给专员核实，后续有进展再向您反馈。');await wait(page,6000);
  await page.getByRole('button',{name:'模拟发送 ↗'}).click();
  await page.locator('.simulated').waitFor();
  assert.equal(await page.locator('.simulated').count(),1);results.push('editable suggested response and local simulated send');await wait(page);
  await page.getByRole('button',{name:'创建跟进',exact:true}).click();await wait(page);
  await page.getByLabel('任务名称',{exact:true}).fill(taskTitle);
  await page.getByLabel('核实说明',{exact:true}).fill('依据 S00010 可见消息与工单，转售后专员核实；不重复索取买家已提供的信息。');await wait(page);
  await page.getByRole('button',{name:'确认创建本地任务'}).click();
  await page.getByText('已创建本地跟进任务；相同任务自动去重',{exact:true}).waitFor();
  await page.getByRole('button',{name:'跟进任务',exact:true}).click();
  await page.getByRole('heading',{name:new RegExp('^'+taskTitle)}).waitFor();await wait(page);
  const task=page.locator('.task-item').filter({has:page.getByRole('heading',{name:new RegExp('^'+taskTitle)})}).first();
  if(await task.getByRole('button',{name:'标记完成'}).count())await task.getByRole('button',{name:'标记完成'}).click();
  await task.getByText('已完成',{exact:true}).waitFor();results.push('task creation and completion persist');
  await page.screenshot({path:path.join(out,'05-tasks.png')});await wait(page,5000);
  await page.getByRole('button',{name:'数据评估',exact:true}).click();
  await page.getByRole('heading',{name:'各场景识别情况'}).waitFor();
  assert.equal(await page.locator('tbody tr').count(),10);results.push('evaluation panel renders all classes');
  await page.screenshot({path:path.join(out,'06-evaluation.png')});await wait(page,6500);
  await page.getByRole('button',{name:'接待工作台',exact:true}).click();
  await page.getByRole('button',{name:'重新分析 ↻'}).click();
  await page.locator('.error-box').waitFor();results.push('no-key fallback is visibly safe');await wait(page,4500);
  const downloadPromise=page.waitForEvent('download');
  await page.getByRole('button',{name:'导出记录 ↓'}).click();
  const download=await downloadPromise;
  await download.saveAs(path.join(out,'sample-session.json'));results.push('JSON snapshot export');
  await page.getByRole('searchbox').fill('<script>');
  await page.getByText('没有匹配的会话。试试其他关键词或筛选。').waitFor();results.push('empty search and escaped input');
  await page.getByRole('searchbox').fill('');
  for(const width of [1440,1024,768,390,320]){
    await page.setViewportSize({width,height:900});
    const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1);
    assert.equal(overflow,false,`horizontal overflow at ${width}`);
    if(width===390) await page.screenshot({path:path.join(out,'07-mobile.png'),fullPage:true});
    results.push(`no page overflow at ${width}px`);
  }
  await page.setViewportSize({width:1512,height:982});
  await page.keyboard.press('Tab');
  assert.ok(await page.evaluate(()=>document.activeElement!==document.body));results.push('keyboard focus available');
  assert.deepEqual(errors,[]);
  const video=record?page.video():null;
  await context.close();
  if(video) await video.saveAs(path.join(out,'demo.webm'));
  await browser.close();
  const report={passed:results.length,checks:results,browser:'Microsoft Edge / Playwright',console_errors:errors,recorded:record};
  fs.writeFileSync(path.join(out,'browser-checks.json'),JSON.stringify(report,null,2));
  console.log(JSON.stringify(report,null,2));
})().catch(err=>{console.error(err);process.exit(1);});
